version: '3.5'

services:
        frontend:
                build: ./ml-kurkkumopo-frontend
                container_name: ml-front
                ports:
                        - 3000:3000
        
        backend:
                build: ./ml-kurkkumopo-backend
                container_name: ml-back
                ports:
                        - 5000:5000
                volumes:
                        - ml-model:/src/model
                depends_on:
                        - training


        training:
                build: ./ml-kurkkumopo-training
                container_name: ml-training
                volumes:
                        - ml-imgs:/src/imgs
                        - ml-data:/src/data
                        - ml-model:/src/model
volumes:
        ml-imgs:
        ml-data:
        ml-model:
